parameters:
- name: Subscription
  type: string
- name: PublishProfile
  type: string
  values: ['Int', 'Prod']
- name: DeploymentEnvironment
  type: string
- name: VariableGroup
  type: string
- name: MaestroTestEndpoints
  type: string
- name: BarConnectionString
  type: string
- name: BarMigrationSubscription
  type: string

# --- Secret Variable group requirements ---
# scenario-test-maestro-token
# dn-bot-dnceng-build-rw-code-rw-release-rw
# maestro-scenario-test-github-token

stages:
- template: /eng/templates/stages/secret-validation.yml@self
  parameters:
    verifyOnly: true

- stage: approval
  dependsOn:
  - build
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/production')}}:
    - publish_using_darc
  jobs:
  - deployment: approval
    displayName: deployment approval (conditional)
    environment: ${{ parameters.DeploymentEnvironment }}
    pool: server
    strategy:
      runOnce:
        deploy: {}

- stage: deploy
  displayName: Deploy
  dependsOn:
  - build
  - approval
  
  variables:
  - name: currentDate
    value: $[format('{0:yyyy}-{0:MM}-{0:dd}', pipeline.startTime)]
  - group: ${{ parameters.VariableGroup }}
  
  jobs:
  - job: updateDatabase
    displayName: Update BuildAssetRegistry database
    steps:
    - download: current
      artifact: ReleaseUtilities

    - task: AzureCLI@2
      displayName: Entity Framework update
      inputs:
        azureSubscription: ${{ parameters.BarMigrationSubscription }}
        scriptType: ps
        scriptLocation: inlineScript
        inlineScript: |
          .\eng\common\build.ps1 -restore -build -projects src\Maestro\Maestro.Data\Maestro.Data.csproj
          .\.dotnet\dotnet tool restore
          .\.dotnet\dotnet ef database update                           `
            --project .\src\Maestro\Maestro.Data\Maestro.Data.csproj    `
            --msbuildprojectextensionspath .\artifacts\obj\Maestro.Data `
            --no-build                                                  `
            --verbose
      env:
        BUILD_ASSET_REGISTRY_DB_CONNECTION_STRING: ${{ parameters.BarConnectionString }}

  - job: deployMaestro
    displayName: Deploy Maestro
    timeoutInMinutes: 85
    dependsOn:
    - updateDatabase
    
    steps:
    - download: current
      artifact: MaestroApplication

    - download: current
      artifact: ReleaseUtilities

    - download: current
      artifact: AssetManifests

    - powershell: |
        $xmlPaths = Get-ChildItem $(Pipeline.Workspace)/AssetManifests/ -Filter *.xml
        $xml = [xml](Get-Content $xmlPaths[0].FullName)
        $releaseVersion = $xml.Build.Package[0].Version
        gh release create "v$(Build.BuildNumber)-$releaseVersion" `
          --generate-notes `
          --latest `
          --title "Rollout $(currentDate) / $(Build.BuildNumber)" `
          --target $(Build.SourceVersion) `
          --notes "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)" `
          --repo dotnet/arcade-services
      displayName: Create GitHub release
      env:
        GH_TOKEN: $(BotAccount-dotnet-bot-repo-PAT)
      continueOnError: true