name: $(Date:yyyyMMdd)$(Rev:r)

stages:
  - stage: PublishConductor
    displayName: Publish Conductor
    dependsOn: []
    jobs:
      - job: Publish
        displayName: Publish Conductor
        pool:
          vmImage: ubuntu-latest

        variables:
          - group: dkurepa-test

        steps:
          - checkout: self

          - powershell: |
              $shortSha = "$(Build.SourceVersion)".Substring(0,10)
              $newDockerTag = "$shortSha-$(Build.BuildNumber)"
              Write-Host "##vso[task.setvariable variable=newDockerImageTag]$newDockerTag"
              Write-Host "set newDockerImageTag to $newDockerTag"
            displayName: 'Set new docker image tag variable'

          - powershell: |
              docker build --progress=plain . -f $(Build.SourcesDirectory)/src/ProductConstructionService/ProductConstructionService.Api/Dockerfile -t dkurepaacr.azurecr.io/conductor.api:$(newDockerImageTag)
              echo $(container-registry-password) | docker login --username $(container-registry-username) --password-stdin "dkurepaacr.azurecr.io"
              docker push "dkurepaacr.azurecr.io/conductor.api:$(newDockerImageTag)"

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'dkurepa-test'
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: '$(Build.SourcesDirectory)/eng/deployment/product-construction-service-deploy.ps1'
              arguments: -resourceGroupName "dkurepa-containers2" -containerappName "apiservice" -newImageTag $(newDockerImageTag) -containerRegistryName "dkurepaacr" -imageName "conductor.api" -subscriptionName "dkurepa dev subscription" -containerappEnvironmentName "acaexjpe3hisjmv2e"