variables:
# For $(DncEngInternalBuildPool) used below
- template: /eng/common/templates-official/variables/pool-providers.yml@self
# Cannot use key:value syntax in root defined variables
- name: _TeamName
  value: DotNetCore
- name: _PublishUsingPipelines
  value: true
- name: _DotNetArtifactsCategory
  value: .NETCore
- name: AzdoOrgUri
  value: https://dev.azure.com/dnceng
- name: AzdoProject
  value: internal
- group: SDL_Settings

trigger:
  batch: true
  branches:
    include:
    - main
    - production

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: $(DncEngInternalBuildPool)
      image: 1es-windows-2019
      os: windows
    
    customBuildTags:
    - ES365AIMigrationTooling
    
    stages:
    - stage: build
      dependsOn: []
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          artifacts:
            publish:
              logs: true
              ${{ if in(variables['Build.SourceBranch'], 'refs/heads/main', 'refs/heads/production') }}:
                artifacts: true
                manifests: true
          enableTelemetry: true
          enableMicrobuild: false
          enablePublishTestResults: false
          enablePublishUsingPipelines: ${{ variables._PublishUsingPipelines }}
          
          jobs:
          - job: Windows_NT
            timeoutInMinutes: 90
            
            pool:
              name: $(DncEngInternalBuildPool)
              image: 1es-windows-2019
              os: windows

            variables:
            # DotNet-Symbol-Server-Pats provides: microsoft-symbol-server-pat, symweb-symbol-server-pat
            # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
            - group: DotNet-Symbol-Server-Pats
            - group: Publish-Build-Assets
            - group: MaestroProd KeyVault
            - _InternalBuildArgs: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName)
                /p:DotNetPublishUsingPipelines=$(_PublishUsingPipelines)
                /p:DotNetArtifactsCategory=$(_DotNetArtifactsCategory)
                /p:DotNetSymbolServerTokenMsdl=$(microsoft-symbol-server-pat)
                /p:DotNetSymbolServerTokenSymWeb=$(symweb-symbol-server-pat)
                /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
            
            - _BuildConfig: Release
            - _PublishType: blob
            - _SignType: test
            
            steps:
            - checkout: self
              clean: true

            - powershell: gh release create "staging-test" --generate-notes --latest --title "StagingTest" --target $(Build.SourceVersion) --repo dotnet/arcade-services
              displayName: Create Release
              env:
                GH_TOKEN: $(BotAccount-dotnet-maestro-bot-PAT)