stages:
  - stage: PublishConductor
    displayName: Publish Conductor
    dependsOn: []
    jobs:
      - job: Publish
        displayName: Publish Conductor
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self

          - powershell: docker build --progress=plain . -f $(Build.SourcesDirectory)/src/Conductor/Conductor.Api/Dockerfile