stages:
  - stage: PublishConductor
    displayName: Publish Conductor
    dependsOn: []
    jobs:
      - job: Publish
        displayName: Publish Conductor
        pool:
          vmImage: ubuntu-latest

        variables:
          - group: dkurepa-test

        steps:
          - checkout: self

          - powershell: |
              docker build --progress=plain . -f $(Build.SourcesDirectory)/src/Conductor/Conductor.Api/Dockerfile
              echo $(container-registry-password) | docker login --username $(container-registry-username) --password-stdin "dkurepaacr.azurecr.io"