stages:
  - stage: PublishConductor
    displayName: Publish Conductor
    dependsOn: []
    jobs:
      - job: Publish
        displayName: Publish Conductor
        pool:
          vmImage: ubuntu-latest

        steps:
          - checkout: self

          - task: powershell
            script: dir

          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              command: build
              Dockerfile: '**/Dockerfile'
              tags: $(Build.SourceVersion)