storageLocation:
  type: azure-key-vault
  parameters:
    subscription: cab65fc3-d077-467d-931f-3932eabf36d3
    name: ProductConstructionInt

secrets:
  build-asset-registry-sql-connection-string:
    type: sql-connection-string
    parameters:
      adminConnection: build-asset-registry-admin-connection-string
      dataSource: tcp:maestro-int-server.database.windows.net,1433
      database: BuildAssetRegistry
      permissions: r
