storageLocation:
  type: azure-key-vault
  parameters:
    subscription: fbd6122a-9ad3-42e4-976e-bccb82486856
    name: ProductConstructionProd

secrets:
  github:
    type: github-app-secret
    parameters:
      hasPrivateKey: true
      hasWebhookSecret: false
      hasOAuthSecret: true
