// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using Microsoft.DotNet.ProductConstructionService.Client.Models;
using Microsoft.DotNet.DarcLib.Models.Darc;
using NUnit.Framework;
using Microsoft.DotNet.DarcLib.Helpers;

#nullable enable
namespace ProductConstructionService.ScenarioTests;

[TestFixture]
[Category("PostDeployment")]
[Category("CodeFlow")]
internal partial class ScenarioTests_CodeFlow : CodeFlowScenarioTestBase
{
    private const string TestFile1Name = "newFile1.txt";
    private const string TestFile2Name = "newFile2.txt";
    private const string DefaultPatch = "@@ -0,0 +1 @@\n+test\n\\ No newline at end of file";

    private static readonly Dictionary<string, string> TestFilesContent = new()
    {
        { TestFile1Name, "test" },
        { TestFile2Name, "test" },
    };

    private static readonly Dictionary<string, string> TestFilePatches = new()
    {
        { $"{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo1Name}/{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo1Name}/{TestFile2Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo2Name}/{TestFile1Name}", DefaultPatch },
        { $"src/{TestRepository.TestRepo2Name}/{VersionFiles.VersionDetailsProps}", "@@ -0,0 +1,11 @@\n+<?xml version=\"1.0\" encoding=\"utf-8\"?>\n+<!--\n+This file is auto-generated by the Maestro dependency flow system.\n+Do not edit it manually, as it will get overwritten by automation.\n+This file should be imported by eng/Versions.props\n+-->\n+<Project>\n+  <PropertyGroup />\n+  <!--Property group for alternate package version names-->\n+  <PropertyGroup />\n+</Project>" }
    };


    [Test]
    public async Task Vmr_ForwardFlowTest()
    {
        var channelName = GetTestChannelName();
        var branchName = GetTestBranchName();
        var productRepo = GetGitHubRepoUrl(TestRepository.TestRepo1Name);
        var targetBranchName = GetTestBranchName();
        var testPrNumber = 23;

        await CreateTestChannelAsync(channelName);

        var subscriptionId = await CreateForwardFlowSubscriptionAsync(
            channelName,
            TestRepository.TestRepo1Name,
            TestRepository.VmrTestRepoName,
            targetBranchName,
            UpdateFrequency.None.ToString(),
            TestParameters.GitHubTestOrg,
            targetDirectory: TestRepository.TestRepo1Name);

        TemporaryDirectory vmrDirectory = await CloneRepositoryAsync(TestRepository.VmrTestRepoName);
        TemporaryDirectory reposFolder = await CloneRepositoryAsync(TestRepository.TestRepo1Name);
        var newFilePath = Path.Combine(reposFolder.Directory, TestFile1Name);

        await CreateTargetBranchAndExecuteTest(targetBranchName, vmrDirectory.Directory, async () =>
        {
            using (ChangeDirectory(reposFolder.Directory))
            {
                await using (await CheckoutBranchAsync(branchName))
                {
                    // Make a change in a product repo
                    TestContext.WriteLine("Making code changes to the repo");
                    await File.WriteAllTextAsync(newFilePath, TestFilesContent[TestFile1Name]);

                    await GitAddAllAsync();
                    await GitCommitAsync($"Change that would have been made in a pr (#{testPrNumber})");

                    // Push it to github
                    await using (await PushGitBranchAsync("origin", branchName))
                    {
                        var repoSha = (await GitGetCurrentSha()).TrimEnd();

                        // Create a new build from the commit and add it to a channel
                        Build build = await CreateBuildAsync(
                            GetGitHubRepoUrl(TestRepository.TestRepo1Name),
                            branchName,
                            repoSha,
                            "1",
                            []);

                        TestContext.WriteLine("Adding build to channel");
                        await AddBuildToChannelAsync(build.Id, channelName);

                        TestContext.WriteLine("Triggering the subscription");
                        // Now trigger the subscription
                        await TriggerSubscriptionAsync(subscriptionId);

                        TestContext.WriteLine("Verifying subscription PR");
                        var pr = await CheckForwardFlowGitHubPullRequest(
                            [(TestRepository.TestRepo1Name, repoSha)],
                            TestRepository.VmrTestRepoName,
                            targetBranchName,
                            [$"src/{TestRepository.TestRepo1Name}/{TestFile1Name}"],
                            TestFilePatches);

                        await CheckIfPullRequestCommentExists(
                            TestRepository.VmrTestRepoName,
                            pr,
                            [$"https://github.com/maestro-auth-test/maestro-test1/pull/{testPrNumber}"]);
                    }
                }
            }
        });
    }

    [Test]
    public async Task Vmr_BackwardFlowTest()
    {
        var channelName = GetTestChannelName();
        var branchName = GetTestBranchName();
        var productRepo = GetGitHubRepoUrl(TestRepository.TestRepo2Name);
        var targetBranchName = GetTestBranchName();

        await CreateTestChannelAsync(channelName);

        var subscriptionId = await CreateBackwardFlowSubscriptionAsync(
            channelName,
            TestRepository.VmrTestRepoName,
            TestRepository.TestRepo2Name,
            targetBranchName,
            UpdateFrequency.None.ToString(),
            TestParameters.GitHubTestOrg,
            sourceDirectory: TestRepository.TestRepo2Name);

        string package1 = GetUniqueAssetName("Foo");
        string package2 = GetUniqueAssetName("Bar");
        string pinnedArcade = DependencyFileManager.ArcadeSdkPackageName;
        string pinnedPackage = GetUniqueAssetName("Pinned");
        List<AssetData> source1Assets = GetAssetData(package1, "1.1.0", package2, "2.1.0");
        List<AssetData> pinnedAssets = GetAssetData(pinnedArcade, "1.1.0", pinnedPackage, "2.1.0");
        List<AssetData> source1AssetsUpdated = GetAssetData(package1, "1.17.0", package2, "2.17.0");
        List<AssetData> updatedPinnedAssets = GetAssetData(pinnedArcade, "1.17.0", pinnedPackage, "2.17.0");

        TemporaryDirectory testRepoFolder = await CloneRepositoryAsync(TestRepository.TestRepo2Name);
        string sourceRepoUri = GetGitHubRepoUrl(TestRepository.VmrTestRepoName);
        TemporaryDirectory vmrFolder = await CloneRepositoryAsync(TestRepository.VmrTestRepoName);
        var newFilePath = Path.Combine(vmrFolder.Directory, "src", TestRepository.TestRepo2Name, TestFile1Name);

        await CreateTargetBranchAndExecuteTest(targetBranchName, testRepoFolder.Directory, async () =>
        {
            TestContext.WriteLine("Adding dependencies to target repo");
            await AddDependenciesToLocalRepo(testRepoFolder.Directory, source1Assets, sourceRepoUri);
            await AddDependenciesToLocalRepo(testRepoFolder.Directory, pinnedAssets, sourceRepoUri, pinned: true);

            TestContext.WriteLine("Pushing branch to remote");
            await GitCommitAsync("Add dependencies");

            await using (await PushGitBranchAsync("origin", targetBranchName))
            {
                using (ChangeDirectory(vmrFolder.Directory))
                {
                    await using (await CheckoutBranchAsync(branchName))
                    {
                        // Make a change in the VMR
                        TestContext.WriteLine("Making code changes in the VMR");
                        File.WriteAllText(newFilePath, TestFilesContent[TestFile1Name]);

                        await GitAddAllAsync();
                        await GitCommitAsync("Add new file");

                        // Push it to github
                        await using (await PushGitBranchAsync("origin", branchName))
                        {
                            var repoSha = (await GitGetCurrentSha()).TrimEnd();

                            // Create a new build from the commit and add it to a channel
                            Build build = await CreateBuildAsync(
                                GetGitHubRepoUrl(TestRepository.VmrTestRepoName),
                                branchName,
                                repoSha,
                                "1",
                                [ ..source1AssetsUpdated, ..updatedPinnedAssets ]);

                            TestContext.WriteLine("Adding build to channel");
                            await AddBuildToChannelAsync(build.Id, channelName);

                            TestContext.WriteLine("Triggering the subscription");
                            // Now trigger the subscription
                            await TriggerSubscriptionAsync(subscriptionId);

                            TestContext.WriteLine("Verifying subscription PR");
                            var assetsToVerify = pinnedAssets
                                .Concat(source1AssetsUpdated)
                                .Select(a => new DependencyDetail() { Name = a.Name, Version = a.Version}).ToList();
                            await CheckBackwardFlowGitHubPullRequest(
                                TestRepository.VmrTestRepoName,
                                TestRepository.TestRepo2Name,
                                targetBranchName,
                                [TestFile1Name],
                                TestFilePatches,
                                assetsToVerify,
                                repoSha,
                                build.Id);
                        }
                    }
                }
            }
        });
    }

    [Test]
    public async Task Vmr_InterleavedBackflowAndForwardFlowTest()
    {
        var channelName = GetTestChannelName();
        var branchName = GetTestBranchName();

        using TemporaryDirectory vmrDirectory = await CloneRepositoryAsync(TestRepository.VmrTestRepoName);
        using TemporaryDirectory repoDirectory = await CloneRepositoryAsync(TestRepository.TestRepo1Name);

        var firstBackflowFileInVmr = Path.Combine(vmrDirectory.Directory, "src", TestRepository.TestRepo1Name, TestFile1Name);
        var forwardFlowFileInRepo = Path.Combine(repoDirectory.Directory, TestFile2Name);
        var repoOnlyFileInRepo = Path.Combine(repoDirectory.Directory, "newFile3.txt");
        var secondBackflowFileInVmr = Path.Combine(vmrDirectory.Directory, "src", TestRepository.TestRepo1Name, "newFile4.txt");
        var secondBackflowFileInRepo = Path.Combine(repoDirectory.Directory, "newFile4.txt");

        await CreateTargetBranchAndExecuteTest(branchName, vmrDirectory.Directory, async () =>
        {
            await CreateTargetBranchAndExecuteTest(branchName, repoDirectory.Directory, async () =>
            {
                await CreateTestChannelAsync(channelName);

                var backflowSubscriptionId = await CreateBackwardFlowSubscriptionAsync(
                    channelName,
                    TestRepository.VmrTestRepoName,
                    TestRepository.TestRepo1Name,
                    branchName,
                    UpdateFrequency.None.ToString(),
                    TestParameters.GitHubTestOrg,
                    sourceDirectory: TestRepository.TestRepo1Name);

                var forwardFlowSubscriptionId = await CreateForwardFlowSubscriptionAsync(
                    channelName,
                    TestRepository.TestRepo1Name,
                    TestRepository.VmrTestRepoName,
                    branchName,
                    UpdateFrequency.None.ToString(),
                    TestParameters.GitHubTestOrg,
                    targetDirectory: TestRepository.TestRepo1Name);

                TestContext.WriteLine("Mimicking repo-main <-> vmr-main with one branch in each repo");

                TestContext.WriteLine("Making a change in the VMR and opening a backflow PR");
                await ChangeAndPushAFile(
                    vmrDirectory.Directory,
                    firstBackflowFileInVmr,
                    "content #1 from the VMR",
                    "Open the first backflow");

                string vmrSha;
                using (ChangeDirectory(vmrDirectory.Directory))
                {
                    vmrSha = (await GitGetCurrentSha()).TrimEnd();
                }

                Build vmrBuild = await CreateBuildAsync(
                    GetGitHubRepoUrl(TestRepository.VmrTestRepoName),
                    branchName,
                    vmrSha,
                    "1",
                    []);

                await AddBuildToChannelAsync(vmrBuild.Id, channelName);
                await TriggerSubscriptionAsync(backflowSubscriptionId);

                var backflowPr = await WaitForPullRequestAsync(TestRepository.TestRepo1Name, branchName);
                await using var backflowPrCleanup = CleanUpPullRequestAfter(
                    TestParameters.GitHubTestOrg,
                    TestRepository.TestRepo1Name,
                    backflowPr);

                TestContext.WriteLine("Making a change in the repo and opening a forward flow PR");
                await ChangeAndPushAFile(
                    repoDirectory.Directory,
                    forwardFlowFileInRepo,
                    "content #1 from the repo",
                    "Open the forward flow");

                string repoSha;
                using (ChangeDirectory(repoDirectory.Directory))
                {
                    repoSha = (await GitGetCurrentSha()).TrimEnd();
                }

                Build repoBuild = await CreateBuildAsync(
                    GetGitHubRepoUrl(TestRepository.TestRepo1Name),
                    branchName,
                    repoSha,
                    "2",
                    []);

                await AddBuildToChannelAsync(repoBuild.Id, channelName);
                await TriggerSubscriptionAsync(forwardFlowSubscriptionId);

                var forwardPr = await WaitForPullRequestAsync(TestRepository.VmrTestRepoName, branchName);
                await using var forwardPrCleanup = CleanUpPullRequestAfter(
                    TestParameters.GitHubTestOrg,
                    TestRepository.VmrTestRepoName,
                    forwardPr);

                var vmrRepo = await GitHubApi.Repository.Get(TestParameters.GitHubTestOrg, TestRepository.VmrTestRepoName);
                await MergePullRequestAsync(TestRepository.VmrTestRepoName, forwardPr);
                await WaitForMergedPullRequestAsync(TestRepository.VmrTestRepoName, branchName, forwardPr, vmrRepo);

                using (ChangeDirectory(vmrDirectory.Directory))
                {
                    await RunGitAsync("fetch", "origin", branchName);
                    await RunGitAsync("checkout", branchName);
                    await RunGitAsync("reset", "--hard", $"origin/{branchName}");
                }

                backflowPr = await GitHubApi.PullRequest.Get(TestParameters.GitHubTestOrg, TestRepository.TestRepo1Name, backflowPr.Number);
                Assert.That(backflowPr.State.Value, Is.EqualTo(Octokit.ItemState.Open), "The backflow PR should remain open while the histories collide");

                TestContext.WriteLine("Pushing another repo change without triggering flow");
                await ChangeAndPushAFile(
                    repoDirectory.Directory,
                    repoOnlyFileInRepo,
                    "content #2 from the repo, not flowed",
                    "Push repo-only change");

                var openForwardPrs = await GitHubApi.PullRequest.GetAllForRepository(
                    vmrRepo.Id,
                    new Octokit.PullRequestRequest
                    {
                        Base = branchName,
                        State = Octokit.ItemStateFilter.Open,
                    });

                Assert.That(openForwardPrs, Is.Empty, "No new forward flow PR should exist until the subscription is triggered again");

                TestContext.WriteLine("Making another VMR change and triggering backflow again");
                await ChangeAndPushAFile(
                    vmrDirectory.Directory,
                    secondBackflowFileInVmr,
                    "content #2 from the VMR",
                    "Open the second backflow");

                using (ChangeDirectory(vmrDirectory.Directory))
                {
                    vmrSha = (await GitGetCurrentSha()).TrimEnd();
                }

                vmrBuild = await CreateBuildAsync(
                    GetGitHubRepoUrl(TestRepository.VmrTestRepoName),
                    branchName,
                    vmrSha,
                    "3",
                    []);

                await AddBuildToChannelAsync(vmrBuild.Id, channelName);
                await TriggerSubscriptionAsync(backflowSubscriptionId);

                var updatedBackflowPr = await WaitForUpdatedPullRequestAsync(TestRepository.TestRepo1Name, branchName);
                Assert.That(updatedBackflowPr.Number, Is.EqualTo(backflowPr.Number), "The second backflow should update the existing PR");

                await WaitForFileContentInPullRequest(
                    repoDirectory.Directory,
                    TestRepository.TestRepo1Name,
                    branchName,
                    secondBackflowFileInRepo,
                    "content #2 from the VMR");
            });
        });
    }
}
